repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.2  # Use the latest version of Ruff
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format